# Generated by Django 5.1.1 on 2024-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_backenduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='backenduser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='backenduser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=7, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='backenduser',
            name='is_admin',
            field=models.BooleanField(help_text='Designate that this user has Admin access of Backend Site', verbose_name='Admin Status'),
        ),
    ]
