# Generated by Django 5.1.1 on 2024-10-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_backenduser_avatar_alter_backenduser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenduser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/avatar.png', upload_to='', verbose_name='Avatar'),
        ),
    ]
